esphome:
  name: etrv2wifi
  comment: Extend Danfoss ECO eTRV BLE range over WiFi with ESPHome
  platform: ESP32
  board: esp32dev
  libraries:
    - xxtea-iot-crypt@2.0.1

# Enable logging
logger:
  level: INFO
  logs:
    esp32_ble_tracker: WARN
    ble_client: WARN
    wifi: INFO
    logger: NONE

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "ssid"
  password: "pass"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Eco2-Room Fallback Hotspot"
    password: "jgwPhdtTWG3m"

captive_portal:

external_components:
  - source: components

# it's not possible to disable the tracker, but at least we won't consume extra energy from the devices during scans
esp32_ble_tracker:
  scan_parameters:
    active: false

ble_client:
  - mac_address: 00:04:2f:40:57:b0
    id: room_eco2

sensor:
  - platform: wifi_signal
    name: "etrv2wifi Signal Sensor"
    update_interval: 60s

climate:
  - platform: danfoss_eco
    name: "My Room eTRV"
    ble_client_id: room_eco2
    pin_code: "0000"
    secret_key: deadbeefcafebabedeadbeefcafebabe 
    battery_level:
      name: "My Room eTRV Battery Level"
    temperature:
      name: "My Room eTRV Temperature"
    update_interval: 60s